networks:
  metrodelay:
    driver: bridge

services:
  remote-resources:
    image: metrodelay/remote-resources:0.0.1
    container_name: remote-resources
    networks:
      - metrodelay
  metrodelay-ws-rest:
    image: metrodelay/metrodelay-rest:0.0.1
    container_name: metrodelay-rest
    networks:
      - metrodelay
  alloy:
    container_name: alloy
    image: grafana/alloy:v1.12.2
    hostname: alloy
    ports:
      - "12345:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    networks:
      - metrodelay
    volumes:
      - type: bind
        source: ./alloy/config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: ./alloy/endpoints.json
        target: /etc/alloy/endpoints.json
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock      
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    deploy:
      resources:
        limits:
          memory: 96M