networks:
  metrodelay:
    driver: bridge
  grafana:
    driver: bridge
    name: grafana

services:
  remote-resources:
    image: metrodelay/remote-resources:0.0.4
    container_name: remote-resources
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=70 -XshowSettings:vm
    networks:
      - metrodelay
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 192M
        limits:
          cpus: '0.4'
          memory: 224M
  metrodelay-storage:
    image: metrodelay/metrodelay-storage:0.0.4
    container_name: metrodelay-storage
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=70 -XshowSettings:vm
    networks:
      - metrodelay
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 128M
        limits:
          cpus: '0.4'
          memory: 192M
  metrodelay-rest:
    image: metrodelay/metrodelay-rest:0.0.4
    container_name: metrodelay-rest
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=70 -XshowSettings:vm
    networks:
      - metrodelay
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 128M
        limits:
          cpus: '0.4'
          memory: 192M
  alloy:
    container_name: metrodelay_alloy
    image: grafana/alloy:v1.14.0
    hostname: alloy
    ports:
      - "12346:12345"
      - "12349:12348"
      - "6833:6832"
      - "55680:55679"
      - "4319:4317"
      - "4320:4318"
    networks:
      - metrodelay
    volumes:
      - type: bind
        source: ./alloy/config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: /var/log
        target: /var/log
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    deploy:
      resources:
        limits:
          memory: 96M
