networks:
  metrodelay:
    driver: bridge

services:
  remote-resources:
    image: ewr.vultrcr.com/metrodelay/remote-resources:0.0.1
    container_name: remote-resources
    networks:
      - metrodelay
  metrodelay-ws-rest:
    image: ewr.vultrcr.com/metrodelay/metrodelay-ws-rest:0.0.1
    container_name: metrodelay-ws-rest
    networks:
      - metrodelay
#  promtail:
#    container_name: promtail
#    image: grafana/promtail:3.2.2
#    hostname: promtail
#    networks:
#      - metrodelay
#    volumes:
#      - type: bind
#        source: ./promtail.yaml
#        target: /etc/promtail/promtail.yaml
#      - type: bind
#        source: /var/log
#        target: /var/log
#      - type: bind
#        source: /var/lib/docker/containers
#        target: /var/lib/docker/containers
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock        
#    command: "-config.file=/etc/promtail/promtail.yaml"
  alloy:
    container_name: alloy
    image: grafana/alloy:v1.11.3
    hostname: alloy
    ports:
      - "12345:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    networks:
      - metrodelay
    volumes:
      - type: bind
        source: ./config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: ./endpoints.json
        target: /etc/alloy/endpoints.json
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock      
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]