networks:
  metrodelay:
    driver: bridge

services:
  remote-resources:
    image: fra.vultrcr.com/metrodelay/remote-resources:0.0.4
    container_name: remote-resources
    hostname: remote-resources
    environment:
      - JAVA_OPTS=-XX:MaxRAM=208m -XX:MaxRAMPercentage=65 -XX:MaxMetaspaceSize=48m -XX:ReservedCodeCacheSize=32m -XshowSettings:vm -XX:NativeMemoryTracking=summary
    ports:
      - "9002:9002"
    networks:
      - metrodelay
    volumes:
      - type: bind
        source: ./heapdumps
        target: /var/log/heapdumps
    command: ["-i", "pt2m", "-d", "pt2m", "-xp", "9002"]
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 192M
        limits:
          cpus: '0.4'
          memory: 224M
  metrodelay-storage:
    image: fra.vultrcr.com/metrodelay/metrodelay-storage:0.0.4
    container_name: metrodelay-storage
    hostname: metrodelay-storage
    environment:
      - JAVA_OPTS=-XX:MaxRAM=176m -XX:MaxRAMPercentage=65 -XX:MaxMetaspaceSize=48m -XX:ReservedCodeCacheSize=32m -XshowSettings:vm -XX:NativeMemoryTracking=summary
    ports:
      - "8001:8001"
      - "9001:9001"
    networks:
      - metrodelay
    command: ["-p", "8001", "-xp", "9001"]
    volumes:
      - type: bind
        source: ./heapdumps
        target: /var/log/heapdumps
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 128M
        limits:
          cpus: '0.4'
          memory: 192M
  metrodelay-rest:
    image: fra.vultrcr.com/metrodelay/metrodelay-rest:0.0.4
    container_name: metrodelay-rest
    hostname: metrodelay-rest
    environment:
      - JAVA_OPTS=-XX:MaxRAM=176m -XX:MaxRAMPercentage=65 -XX:MaxMetaspaceSize=48m -XX:ReservedCodeCacheSize=32m -XshowSettings:vm -XX:NativeMemoryTracking=summary
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - type: bind
        source: ./heapdumps
        target: /var/log/heapdumps
    networks:
      - metrodelay
    command: ["-p", "8000", "-xp", "9000"]
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 128M
        limits:
          cpus: '0.4'
          memory: 192M
  alloy:
    container_name: alloy
    image: grafana/alloy:v1.14.1
    hostname: alloy
    user: root
    cap_add:
      - SYS_PTRACE
      - DAC_READ_SEARCH
    pid: host
    network_mode: host
    volumes:
      - type: bind
        source: ./config.alloy
        target: /etc/alloy/config.alloy
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--cluster.enabled=false",
      "--disable-reporting",
      "/etc/alloy/config.alloy",
    ]
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 192M
        limits:
          cpus: '0.4'
          memory: 256M