- hosts: localhost
  gather_facts: no
  tasks:  
  - name: list instances
    vultr.cloud.instance_info:
      region: "fra"
      label: "o11y"
      api_key: "{{ vultr.api_key }}"
  - name: create instance
    vultr.cloud.instance:
      region: "fra"
      api_key: "{{ vultr.api_key }}"
      backups: false
      hostname: o11y-{{ cluster }}
      os: Alpine Linux x64
      label: o11y
      tags:
        - o11y
        - blue
      plan: vc2-1c-1gb
      ssh_keys:
        - ansible
      user_scheme: root
  - name: list instances
    vultr.cloud.instance_info:
      region: "fra"
      label: "o11y"
      api_key: "{{ vultr.api_key }}"